language: go

go:
  - 1.12.x

install: true

env:
  - HELM_HOST=127.0.0.1:44134
  - TILLER_HOST=127.0.0.1:44134
  - HELM_HOME=${HOME}/.helm
  - HELM_PATH_REPOSITORY_FILE=${HELM_HOME}/repository/repositories.yaml

before_script:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only
  - helm plugin install https://github.com/rimusz/helm-tiller
  - helm tiller start-ci
  - source <(helm tiller env)
  - curl https://glide.sh/get | sh
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - source <(helm tiller env)
  - make bootstrap build helmrel cov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - helm tiller stop
